name: obesity-risk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24,<2
  - pandas>=2.0,<3
  - scikit-learn>=1.3,<2
  - matplotlib>=3.7,<4
  - seaborn>=0.12,<0.14
  - phik>=0.12,<0.13
  - pyyaml>=6.0,<7
  - joblib>=1.3
  - nbformat>=5.9
  - pip
  - ipykernel